name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Golang setup
        id: golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Run tests
        run: |
          echo "Running tests..." # TODO: Add tests

      - name: Build Go Application
        run: |
          go build -o myapp ./cmd/main.go

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Geração da tag
      - name: Generate tag
        id: generate-tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: . # O contexto de construção do Docker ('.' significa o diretório atual)
          push: true # Se true, a imagem Docker será enviada para o registro
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.generate-tag.outputs.sha }}
          cache-from: type=gha # Habilita o cache de camadas do Docker para construções mais rápidas
